= Tools
:author: Karl Sigurdsson
:email: karl.sigurdsson@gmail.com
:revnumber: v0.1
:revdate: February 16, 2018
:toc: left
:toclevels: 3
:icons: font
:sectnums:
:sectnumlevels: 2

== Overview

This repository provides development tools that I use regularly. To make
these tools portable across macOS, Linux and Windows they are typically
packaged to run as Docker containers.

== Prerequisites

* Windows Subsystem for Linux (WSL)
* Environment Modules
* Homebrew (macOS package manager)
* Docker

== Environment Modules

Install and configure environment modules

=== Windows
 sudo apt-get install environment-modules

Add the following to .cshrc
 source /usr/share/modules/init/tcsh
 setenv MODULEPATH ${HOME}/tools/modulefiles

=== macOS
 brew install modules

== Install Docker

Due to some tools requiring access to USB (namely sigrok logic analyser) use
Docker Toolbox rather than native Docker for Mac/Windows as it uses
VirtualBox to run the virtual machine which (unlike Hyper-V or bHyve).

=== Windows
**Download and install DockerToolBox:** https://download.docker.com/win/stable/DockerToolbox.exe

Install packages to allow apt to use a repository over HTTPS

 sudo apt-get install apt-transport-https ca-certificates curl software-properties-common

Add Docker's official GPG key

 curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

Set up the repository

 sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

Update source lists

 sudo apt-get update

Install Docker

 sudo apt-get install docker-ce

== Create a Docker Machine

=== Windows

 module add docker
 docker-machine create --driver virtualbox --virtualbox-memory=4096 --virtualbox-cpu-count=2 --virtualbox-disk-size=20000 main
 
== Start Docker Machine

 docker-machine start main
 setenv DOCKER_TLS_VERIFY "1";
 setenv DOCKER_HOST "tcp://192.168.99.103:2376";
 setenv DOCKER_CERT_PATH "/mnt/c/Users/karls/.docker/machine/machines/main";
 setenv DOCKER_MACHINE_NAME "main";

== Stop Docker Machine

 docker-machine stop main

== Windows WSL Usage Instructions

. Enable the WSL tools
 module add wsl
. Start docker machine
 docker-machine start main
. Setup docker machine
 docker-machine env main --shell=tcsh
. Now set the environment variables - converting to a wsl path (script this
 in future)
