FROM ubuntu:16.04

# Install required packages
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install tcsh nano && \
    rm -rf /var/lib/apt/lists/*

# Create the staff group
#RUN addgroup --gid 20 staff

# Username is passed in as a build argument
ARG username

# Create the user in the image
RUN adduser --disabled-login \
            --gecos '' \
            --home /home/${username} \
            --shell /bin/tcsh \
            ${username}
#            --gid 20 -uid 501 ${username}

#CMD [ "konsole", "-e", "/bin/bash" ]

#USER ${username}
#WORKDIR /home/${username}
