FROM base:16.04

# Install required packages
# ruby required to install the asciidoctor gem
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install \
    make \
    ruby \
    && rm -rf /var/lib/apt/lists/*

# Install asciidoctor
# Note: to install a gem into home area (not requiring root priviledges)
# setenv GEM_HOME $HOME/.gems

RUN gem install asciidoctor && \
    gem install asciidoctor-pdf --pre
